### ISSUE TITLE
2.10.0 doesn't install on 1.41.0 (Linux)

### ISSUE THREAD

**Issue by aaj1** [platformio/platformio-atom-ide-terminal#812]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

```Installing “platformio-ide-terminal@2.10.0” failed.Hide output…

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /tmp/apm-install-dir-1191116-13875-117adnn.x16v/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


internal/modules/cjs/loader.js:964
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-1191116-13875-117adnn.x16v/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch/package.json'
Require stack:
- /usr/lib64/node_modules/prebuild-install/node_modules/napi-build-utils/index.js
- /usr/lib64/node_modules/prebuild-install/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib64/node_modules/prebuild-install/node_modules/napi-build-utils/index.js:5:11)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib64/node_modules/prebuild-install/node_modules/napi-build-utils/index.js',
    '/usr/lib64/node_modules/prebuild-install/bin.js'
  ]
}
internal/modules/cjs/loader.js:964
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-1191116-13875-117adnn.x16v/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch/scripts/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1191116-13875-117adnn.x16v/package.json'
npm WARN apm-install-dir-1191116-13875-117adnn.x16v No description
npm WARN apm-install-dir-1191116-13875-117adnn.x16v No repository field.
npm WARN apm-install-dir-1191116-13875-117adnn.x16v No README data
npm WARN apm-install-dir-1191116-13875-117adnn.x16v No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /aaj/.atom/.apm/_logs/2019-12-16T16_46_41_067Z-debug.log
```

### Steps to reproduce

1. Open Settings->Install
2. Find platformio-ide-terminal 2.10.0
3. Click: Install.

**Expected behavior:** 
The package should install. :)

**Actual behavior:** 
The package doesn't install.

**Reproduces how often:** 
Always.

### Versions

```
> atom --version
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

```
> apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 2.7.17
git 2.24.1
```
OS name and version: Gentoo Linux
Platformio-ide-terminal version: 2.10.0

**Comment by the-j0k3r** [comment]
Unrelated to platformio-ide-terminal 2.1.0,, I can assure you it works with Atom 1.41.0, this is related to install failures and we cant control installers, thats up to apm.

>Error: Cannot find module '/tmp/apm-install-dir-1191116-13875-117adnn.x16v/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch/scripts/install.js'

its pretty clear something failed either it wasnt downloaded or corrupted, try again not using proxies if youre using any, just retry again.

**Comment by aaj1** [comment]
Ech... I'm an idiot... The following fixed my issue:
```
cd $HOME/atom
sudo chown -R $USER:$USER .
```
