### ISSUE TITLE
Atom console: Cannot find module '..\build\Release\pty.node'

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#281]
Hello.

The add-on (**platformio-ide-terminal**) seems to behave as it should. .. on the surface at least.

However... each time a terminal is opened two (2) warnings are triggered. These can be seen in the console (Atom development tools <_CTRL-SHIFT-I_>). The message reads: **Cannot find module '..\build\Release\pty.node'**.

Only recently I have started using Atom's development console for testing native Atom commands and Coffeescript code pieces. Before yesterday I was running a Atom V1.16 and a previous version of the add-on. I do not know if a version is created the issue. 

I observe the **node-module/pty.js/bin** contains win32 but no win64. Could this be an issue? 

How can we fault-find this case? (thank you)
- Dan Padric

----------------------------------------------------
platformio-ide-terminal V2.5.3
IDE........ Atom V1.18.0
OS..........Windows 7 SP1, Professional  
User level: ground-level

**Comment by ghost** [comment]
Hello again.

An update on the before mentioned issue: 
- Fresh install of Atom V1.18.0 on a PC.
- PC: Windows 7 SP1, 64-bit, Professional. 
(As previous PC, but did not have Atom loaded before.)
- Installed package "platformio-ide-terminal V2.5.3" from an internet connection.
- Open Atom Console after installation with message:
  >C:\Users\Dan\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty.js:17
  > &nbsp;&nbsp;Cannot find module '..\build\Release\pty.node'
  > C:\Users\Dan\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty_win.js:16 
  > &nbsp;&nbsp;Cannot find module '..\build\Release\pty.node'

Hope to hear your thoughts on how to proceed.
- Dan Padric

**Comment by ZubairGaj** [comment]
Try clicking on the redbug at the bottom of atom and then clicking re-build packages in the window
Thats what worked for me

**Comment by ghost** [comment]
> Try clicking on the redbug at the bottom of atom and then clicking re-build packages in the window
Thats what worked for me

Hello. 
Thank you for sharing your thoughts. I have seen that red bug previously when I updated Atom to V1.19 last week. I did exactly as what you were thinking of. Some updating process was run, but still did not solve the issue.

The following message in the console:
```
events.js:106 
Cannot find module '..\build\Release\pty.node'
(anonymous) @ <embedded>:70970
(anonymous) @ <embedded>:71047
module.exports.Emitter.simpleDispatch @ <embedded>:63277
module.exports.Emitter.emit @ <embedded>:63393
(anonymous) @ <embedded>:70999
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```
@ZubairGaj - did you check the console for any messages?
_How to add a picture to show the result?_

Regards.

**Comment by ghost** [comment]
Okay... since I am having trouble adding a picture here, I have done so here:
https://discuss.atom.io/t/warning-message-cannot-find-module-build-release-pty-node/46224

Forgive my ignorance - what does "PR Welcome" mean?

**Comment by ghost** [comment]
Perhaps it is worthwhile to look at the conclusion of [LINK](https://discuss.atom.io/t/solved-cannot-find-module-build-release-pty-node/46224)

Very probable my issue is under control now. BUT needing to download a huge chunk of data to be able to compile the required modules does not seem like a `customer` solution.

In spite of this, I would like to thank you for your continued efforts on expanding the original terminal project.
