### ISSUE TITLE
doesn't work with atom 1.12

### ISSUE THREAD

**Issue by sagiegurari** [platformio/platformio-atom-ide-terminal#85]
I'm using windows 10, configured the package to use git bash as the exectuable and it all worked well for some time.
However with the new atom 1.12 beta it is just opening a new panel but the shell inside is not started.
there are no errors in the console.

**Comment by sagiegurari** [comment]
there is an error when opening the console

``` sh
task.coffee:86 Cannot find module '..\bin\win32\ia32.m49.node' Error: Cannot find module '..\bin\win32\ia32.m49.node'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> 
```

**Comment by Dysp** [comment]
+1

**Comment by rdfedor** [comment]
Have the same issue after upgrading to Atom 1.12 on MacOSX,

```
task.coffee:86 Cannot find module '../bin/darwin/x64.m49.node' Error: Cannot find module '../bin/darwin/x64.m49.node'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

then after this appears I get this error,

```
Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

These errors do not appear until after you try opening a new terminal tab.

**Comment by sagiegurari** [comment]
probably need to upgrade nan but I'm not sure if this project is still maintained which is unfortunate.

**Comment by rdfedor** [comment]
Sometimes perfection doesn't need an update lol.  Give em some time, coming from a software engineer background myself, I believe this is ran by company so they'll probably need to schedule time for one of their engineers to check it out during one of their next sprints.

**Comment by alexrussell** [comment]
I think this is the same issue I have. On opening a terminal I get a console warning:

```
Cannot find module '../build/Release/pty.node'
```

Which it says originates in `task.coffee:85` (`file:///Users/distiller/atom/out/app/src/task.coffee`) - presumably from some build process as my user is not `distiller`.

That is followed by an error stacktrace:

```
task.coffee:86 Cannot find module '../bin/darwin/x64.m49.node' Error: Cannot find module '../bin/darwin/x64.m49.node'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alexrussell/.atom/packages/platformio-ide-terminal/node_modules/pty.js/lib/pty.js:18:9)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alexrussell/.atom/packages/platformio-ide-terminal/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alexrussell/.atom/packages/platformio-ide-terminal/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/alexrussell/.atom/packages/platformio-ide-terminal/lib/process.coffee:1:1)
    at Module._compile (module.js:541:32)
    at Object.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/task-bootstrap.js:110:13)
```

Which it says originates in `task.coffee:86` (`file:///Users/distiller/atom/out/app/src/task.coffee`)

And then after that another error stacktrace:

```
Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Which it says also originates in `task.coffee:86` (`file:///Users/distiller/atom/out/app/src/task.coffee`)

Screenshot for full console details.

![terminal error](https://cloud.githubusercontent.com/assets/412784/19552819/6810be8c-96a9-11e6-933f-90265a9ac786.png)

Atom 1.12.0-beta3, OSX 10.11.6.

Is it possible it just failed to build some native module on install (there was no error - popup or console - on install)?

**Comment by ivankravets** [comment]
I see that we will have a tons of problems with new Atom 1.12. They switched to new Electron and other packages that require new NAN and other things. The `pty.js` depends on obsolate `winpty` that doesn't work with new `nan 2.3.5`. I can rebuild all binaries for Unix but need to think what to do with Windows users.

Please don't use Atom 1.12 and wait when we preapre all PTY binaries.

**Comment by sagiegurari** [comment]
Thanks for the update.
v8 upgrade will happen every now and than so it is always best to use latest nan to ensure you are prepared for those upgrades while still supporting older versions.

**Comment by skull-squadron** [comment]
Can't use 1.11 because it breaks some mandatory packages.

**EDIT:** https://github.com/tjmehta/terminal-plus working on 1.12 beta5

`apm i tjmehta/terminal-plus`

**Comment by skull-squadron** [comment]
See also https://github.com/jeremyramin/terminal-plus/pull/364

**Comment by Mehul** [comment]
Was having the exact same issues with installed versions of stable or beta. 

Then I used the stand alone windows exe and installed platformio-ide-terminal package. That seems to work, so far.

**Comment by kachkaev** [comment]
@alexrussell I'm seeing the same error as you on OSX, Atom 1.12-beta7: `Cannot find module '../bin/darwin/x64.m49.node'`. What did you end up doing as a workaround?

**UPD:** OK, here's my temporary workaround: 😆

![screen shot 2016-11-06 at 15 30 47](https://cloud.githubusercontent.com/assets/608862/20039093/182fa578-a436-11e6-8396-417b266a6de4.png)

**Comment by ivankravets** [comment]
Wow.... 12 comments... multiple ups ( 👍 )

Need to resovle this issue...

P.S: Is here someone with Ubuntu?

**Comment by alexrussell** [comment]
@kachkaev haha nice workaround :) And no I didn't find anything that I found particularly satisfactory - like you I'm just using separate terminals for now.

@ivankravets from the looks of comments on both this and the original terminal-plus package (as well as other people's forks) it's all about updating the version numbers (commit references) for the dependent packages pty.js and term.js (I think actually just pty.js). But other than that (presumably they need to have native modules built for each platform and something needs tweaking and that's why the updates are required) I don't know much of the root of the issue.

**Comment by ivankravets** [comment]
@alexrussell we have own PlatformIO's fork of PTY with pre-built binaries. It allows to use PlatformIO IDE Terminal on the machine where compiler is not installed for gyp. 

Yes, I know that we should update `nan` dependcy in pty.js but it will break WinPTY. But...!!! We have great news!  Daniel Imms (@Tyriar) from @microsoft re-forked PlatformIO's PTY and added support for nan 2.2.1! See https://github.com/Tyriar/pty.js/commits/prebuilt

As result, we've just succesfully compiled PTY.JS for Windows and tested on Windows 8/10 and are working on other binaries for macOS & Linux.

Stay tuned! 😊 Also, don't forget to try http://platformio.org 😆

**Comment by alexrussell** [comment]
A-ha good news.

As for trying PlatformIO, I'd love to play around with and learn new things but I have enough on my plate at the moment! :)

**Comment by ivankravets** [comment]
PlatformIO IDE Terminal 2.2.1 is out!

P.S: Atom 1.12 for Linux is not ready. Please comment here if you are Ubuntu owner and would like to help us.

**Comment by kachkaev** [comment]
Awesome!

![screen shot 2016-11-06 at 16 55 00](https://cloud.githubusercontent.com/assets/608862/20039778/dba36016-a441-11e6-953e-7434dfda8f95.png)

(macOS 10.12.1, Atom 1.12-beta 7)

**Comment by sagiegurari** [comment]
works good for me as well. thanks.

**Comment by Tyriar** [comment]
Glad to help 😃 I'm planning on cleaning up the pty.js situation and improving Windows support soon. Follow https://github.com/Microsoft/vscode/issues/13625 if you want to track that development.
