### ISSUE TITLE
Failed to activate the platformio-ide-terminal package

### ISSUE THREAD

**Issue by nihiven** [platformio/platformio-atom-ide-terminal#400]
[Steps to reproduce:]
This bug started after the upgrade to 1.230-beta0 from 1.22.0-beta2.

1. Install the package.
2. Restart Atom.

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.7.0

### Stack Trace

Failed to activate the platformio-ide-terminal package

```
At target[Symbol.iterator] is not a function

TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/tooltip-manager.js:117:35)
    at StatusBar.module.exports.StatusBar.initialize (/packages/platformio-ide-terminal/lib/status-bar.coffee:84:38)
    at /packages/todo-show/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:12:7)
    at Object.consumeStatusBar (/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:28:26)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:456:81)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:258:22)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:1068:34
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:717:40)
    at Promise.all.then (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:650:18)
```

### Non-Core Packages

```
atom-ide-ui 0.5.4 
atom-solarized-dark-ui 0.28.1 
atom-terminal 0.8.0 
autocomplete-python 1.10.3 
autocomplete-python-jedi 1.10.3-0 
busy-signal 1.4.3 
color-picker 2.2.5 
es6-javascript 1.0.0 
github-atom-dark-syntax 0.5.0 
go-plus 5.6.0 
ide-csharp 0.6.0 
ide-python 0.2.3 
ide-typescript 0.6.2 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
linter-ui-plus 0.3.2 
meteor-api 2.20.0 
miami-nights-syntax 0.3.3 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
platformio-ide-terminal 2.7.0 
pure-syntax 0.3.0 
solarized-dark-ui 0.3.2 
solarized-one-dark-syntax 1.1.0 
sort-lines 0.18.0 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.3 
todo-show 2.1.0 
tree-view-git-modified 0.7.3 
vice-city-syntax 0.2.0 
```

**Comment by nihiven** [comment]
Fixed.
