### ISSUE TITLE
platformio-ide-terminal 2.5.5 not working with Atom 1.18.0

### ISSUE THREAD

**Issue by sergiohgz** [platformio/platformio-atom-ide-terminal#299]
Hi there,

I just show that were troubles with Atom 1.19 and, after update, there are problems with Atom 1.18.0. After upgrading platformio-ide-terminal to 2.5.5:
- Package is installed and not working
- No icons for open and close terminals in footer, left side
- No shortcuts working

There is another message as a bug reported by Atom:
 > Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.
> Cannot find module '~/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'

Here you can see that there are no buttons and version.
![captura de pantalla de 2017-08-09 09-15-18](https://user-images.githubusercontent.com/14012309/29109456-5e4f3358-7ce3-11e7-98c2-82f219515c3f.png)

**Comment by sergiohgz** [comment]
It seems that open the bug shown in footer, you can rebuild package and get back the terminal to work well.

I'll leave this open in order to make easier to other users of Atom 1.18 find the solution. Thanks a lot :smile:

**Comment by barayuda** [comment]
Hi @sergiohgz ~~in other open issue #301 
I got blank terminal after update upgrading platformio-ide-terminal to 2.5.5
Need some help to fix.~~ Solved 😄 Thank you

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
