### PR TITLE
Fix button elements not being iterable in Atom-Beta 1.23

### LINKED ISSUE #400: Failed to activate the platformio-ide-terminal package
[Steps to reproduce:]
This bug started after the upgrade to 1.230-beta0 from 1.22.0-beta2.

1. Install the package.
2. Restart Atom.

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.7.0

### Stack Trace

Failed to activate the platformio-ide-terminal package

```
At target[Symbol.iterator] is not a function

TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/tooltip-manager.js:117:35)
    at StatusBar.module.exports.StatusBar.initialize (/packages/platformio-ide-terminal/lib/status-bar.coffee:84:38)
    at /packages/todo-show/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:12:7)
    at Object.consumeStatusBar (/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:28:26)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:456:81)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:258:22)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:1068:34
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:717:40)
    at Promise.all.then (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:650:18)
```

### Non-Core Packages

```
atom-ide-ui 0.5.4 
atom-solarized-dark-ui 0.28.1 
atom-terminal 0.8.0 
autocomplete-python 1.10.3 
autocomplete-python-jedi 1.10.3-0 
busy-signal 1.4.3 
color-picker 2.2.5 
es6-javascript 1.0.0 
github-atom-dark-syntax 0.5.0 
go-plus 5.6.0 
ide-csharp 0.6.0 
ide-python 0.2.3 
ide-typescript 0.6.2 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
linter-ui-plus 0.3.2 
meteor-api 2.20.0 
miami-nights-syntax 0.3.3 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
platformio-ide-terminal 2.7.0 
pure-syntax 0.3.0 
solarized-dark-ui 0.3.2 
solarized-one-dark-syntax 1.1.0 
sort-lines 0.18.0 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.3 
todo-show 2.1.0 
tree-view-git-modified 0.7.3 
vice-city-syntax 0.2.0 
```

### LINKED ISSUE #403: Failed to activate the platformio-ide-terminal package (ATOM BETA 1.23)
target[Symbol.iterator] is not a function
Hide Stack Trace
TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (/usr/share/atom-beta/resources/app/src/tooltip-manager.js:117:35)
    at StatusBar.module.exports.StatusBar.initialize (/home/conradolucas/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee:84:38)
    at StatusBar.View [as constructor] (/home/conradolucas/.atom/packages/pdf-view/node_modules/space-pen/lib/space-pen.js:184:25)
    at new StatusBar (/home/conradolucas/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee:12:7)
    at Object.consumeStatusBar (/home/conradolucas/.atom/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:28:26)
    at Provider.module.exports.Provider.provide (/usr/share/atom-beta/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/usr/share/atom-beta/resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (/usr/share/atom-beta/resources/app/src/package.js:456:81)
    at Package.module.exports.Package.activateNow (/usr/share/atom-beta/resources/app/src/package.js:258:22)
    at /usr/share/atom-beta/resources/app/src/package.js:1068:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at triggeredActivationHooks.forEach.hook (/usr/share/atom-beta/resources/app/src/package-manager.js:705:86)
    at Set.forEach (native)
    at PackageManager.activatePackage (/usr/share/atom-beta/resources/app/src/package-manager.js:705:43)
    at packagesToEnable.forEach.name (/usr/share/atom-beta/resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/usr/share/atom-beta/resources/app/src/package-manager.js:440:30)
    at /usr/share/atom-beta/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom-beta/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/usr/share/atom-beta/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/usr/share/atom-beta/resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom-beta/resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (/usr/share/atom-beta/resources/app/src/package.js:84:32)
    at PackageManager.enablePackage (/usr/share/atom-beta/resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/share/atom-beta/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
The error was thrown from the platformio-ide-terminal package. This issue has already been reported.

**HELP-ME**

### LINKED ISSUE #406: Failed to activate the platformio-ide-terminal package
target[Symbol.iterator] is not a function

TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (/Applications/Atom Beta.app/Contents/Resources/app/src/tooltip-manager.js:117:35)
    at StatusBar.module.exports.StatusBar.initialize (/Users/mirelopxaneb/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee:84:38)
    at StatusBar.View [as constructor] (/Users/mirelopxaneb/.atom/packages/script/node_modules/space-pen/lib/space-pen.js:184:25)
    at new StatusBar (/Users/mirelopxaneb/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee:12:7)
    at Object.consumeStatusBar (/Users/mirelopxaneb/.atom/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:28:26)
    at Provider.module.exports.Provider.provide (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:456:81)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:258:22)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:1068:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at triggeredActivationHooks.forEach.hook (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:705:86)
    at Set.forEach (native)
    at PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:705:43)
    at packagesToEnable.forEach.name (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:440:30)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:84:32)
    at PackageManager.enablePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:361:31)

### PR DESCRIPTION
**Pull request by robertrossmann**
This PR fixes package activation on latest Atom-Beta 1.23.

For whatever reason the button elements do not have the standard `Symbol.iterator` prototype set despite otherwise looking like regular arrays. This PR monkey-patches those array-likes by adding the `Symbol.iterator` so that _tooltip-manager_ can properly iterate over them.

I suspect this to be a bug in Atom itself but I am not certain how or where to fix it so I thought providing at least a temporary workaround for this package's users might be worthwhile. ❤️

Fixes #400
Fixes #403
Fixes #406

### CODE REVIEW

**Comment by MarkoShiva** [comment]
Having the same issue with atom-beta-1.23

**Comment by ivankravets** [comment]
This is a bug of Atom and should be fixed in https://github.com/atom/atom/releases/tag/v1.23.0-beta1

**Comment by robertrossmann** [comment]
It is indeed! 🤘
