### ISSUE TITLE
Not work on Win10 X64, Atom 1.11.2, platformio-ide-terminal 2.2.0

### ISSUE THREAD

**Issue by zhangby01** [platformio/platformio-atom-ide-terminal#95]
Win10 X64 1607(14393.351);
Atom 1.11.2;
platformio-ide-terminal 2.2.0;

When I start terminal, the console will show error:

Cannot find module '..\build\Release\pty.node'        task.coffee:86

Unable to start terminal process. Win32 error code: 267 Error: Unable to start terminal process. Win32 error code: 267
    at Error (native)
    at Server.<anonymous> (C:\Users\Me\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty_win.js:67:9)
    at emitOne (events.js:90:13)
    at Server.emit (events.js:182:7)
    at Pipe.onconnection (net.js:1439:8)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ C:\Users\Me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25module.exports.Emitter.emit @ C:\Users\Me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:129(anonymous function) @ task.coffee:98emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
